name: watch_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_database: ^10.1.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
